[project]
name = "voice-flow-shared"
version = "0.1.0"
description = "Shared utilities for Voice Flow application."
requires-python = ">=3.13"
dependencies = ["sqlalchemy>=2.0.43"]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
