[project]
name = "voice-flow-app"
version = "0.1.0"
description = "Voice Flow Application."
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["agent", "backend", "shared"]

[tool.ruff.lint]
ignore = ["E402"]
